spring:
  application:
    name: front

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"

      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token

        registration:
          front:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: front
            client-secret: front-secret
            scope: profile,email
server:
  port: 8080
customFilterChain:
  needed: false
accounts:
  prefix: accounts
exchange:
  prefix: exchange
gateway:
  prefix: ""
exchange-generator:
  prefix: exchange-generator
cash:
  prefix: cash
blocker:
  prefix: blocker
transfer:
  prefix: transfer
notifications:
  prefix: notifications
management:
  endpoints:
    web:
      exposure:
        include: health,info
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1