spring:
  application:
    name: blocker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8180/realms/master/protocol/openid-connect/certs"
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/master/protocol/openid-connect/token
        registration:
          blocker:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: blocker
            client-secret: blocker-secret
            scope: profile,email
management:
  endpoints:
    web:
      exposure:
        include: health,info
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
server:
  port: 8080
accounts:
  prefix: accounts
exchange:
  prefix: exchange
gateway:
  prefix: ""
exchange-generator:
  prefix: exchange-generator
cash:
  prefix: cash
blocker:
  prefix: blocker
transfer:
  prefix: transfer
notifications:
  prefix: notifications
