spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          accounts:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: accounts
            client-secret: accounts-secret
            scope: profile,email
  kafka:
    bootstrap-servers: 'kafka:9092'
    admin:
      client-id: yandex-practicum
      fail-fast: true
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1000
      acks: all
      properties:
        enable.idempotence: true

blockerService:
  needed: true
notificationsService:
  needed: true

server:
  port: 8080
