apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: bank.local
      http:
        paths:
          - path: /bank(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: front
                port:
                  number: 8080