apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-gateway
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /exchange(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: exchange
                port:
                  number: 8080

          - path: /accounts(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: accounts
                port:
                  number: 8080

          - path: /exchange-generator(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: exchange-generator
                port:
                  number: 8080

          - path: /notifications(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notifications
                port:
                  number: 8080

          - path: /cash(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cash
                port:
                  number: 8080

          - path: /blocker(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: blocker
                port:
                  number: 8080

          - path: /transfer(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transfer
                port:
                  number: 8080