spring:
  security:
    oauth2:
      client:
        registration:
          front:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: front
            client-secret: front-secret
            scope: profile,email
accounts:
  prefix: accounts
gateway:
  prefix: gateway
server:
  port: 8080
