spring:
  application:
    name: exchange
  kafka:
    bootstrap-servers: 'kafka:9092'
    admin:
      client-id: yandex-practicum
      fail-fast: true
    consumer:
      bootstrap-servers: kafka:9092
      group-id: yandex-practicum
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"

      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token

        registration:
          exchange:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: exchange
            client-secret: exchange-secret
            scope: profile,email
server:
  port: 8080
accounts:
  prefix: accounts
exchange:
  prefix: exchange
gateway:
  prefix: ""
exchange-generator:
  prefix: exchange-generator
cash:
  prefix: cash
blocker:
  prefix: blocker
transfer:
  prefix: transfer
notifications:
  prefix: notifications
management:
  endpoints:
    web:
      exposure:
        include: health,info
  zipkin:
    tracing:
      endpoint:  http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1