spring:
  application:
    name: exchange

  security:
    oauth2:
      client:
        registration:
          exchange:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: exchange
            client-secret: exchange-secret
            scope: profile,email
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: beans,conditions,env,configprops,mappings
